%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 640
image_height: 480
distortion_parameters:
   k1: 0.0
   k2: 0.0
   p1: 0.0
   p2: 0.0
projection_parameters:
   fx: 611.4509887695312
   fy: 611.4857177734375
   cx: 330.00
   cy: 249.4730224609375
